"""
Central path settings for the Air-Quality-Forecasting-System.

This module defines absolute Path objects for all critical directories and files 
within the repository. Using Pathlib ensures cross-platform compatibility (Windows/Linux/macOS).

Location: src/config/settings.py
Project Structure:
    <repo_root>/
    ├── data/           # Raw and processed datasets
    ├── outputs/        # Generated artifacts (models, plots, alerts)
    └── src/            # Source code and configurations
"""

from pathlib import Path

# --- Root Directory Resolution ---
# Resolve the absolute path to the repository root.
# .parents[2] navigates up from: src/config/settings.py -> src/config/ -> src/ -> <repo_root>/
REPO_ROOT: Path = Path(__file__).resolve().parents[2]

# --- Top-Level Directory Definitions ---
SRC_DIR: Path = REPO_ROOT / "src"
DATA_DIR: Path = REPO_ROOT / "data"
OUTPUTS_DIR: Path = REPO_ROOT / "outputs"

# --- Data Assets ---
# raw/: Original, immutable data
# processed/: Cleaned data ready for model consumption
RAW_DATA_DIR: Path = DATA_DIR / "raw"
PROCESSED_DATA_DIR: Path = DATA_DIR / "processed"
RAW_AIR_QUALITY_CSV: Path = RAW_DATA_DIR / "AirQualityUCI.csv"

# --- Configuration Management ---
# YAML files containing hyperparameters, alert levels, and feature lists
CONFIG_DIR: Path = SRC_DIR / "config"
CONFIGS_SUBDIR: Path = CONFIG_DIR / "configs"
ALERTS_CONFIG_YAML: Path = CONFIGS_SUBDIR / "alerts.yaml"
FEATURES_CONFIG_YAML: Path = CONFIGS_SUBDIR / "features.yaml"
MODELS_CONFIG_YAML: Path = CONFIGS_SUBDIR / "models.yaml"

# --- Core Logic & Model Scripts ---
# Primary entry point for training
TRAIN_MODELS_SCRIPT: Path = REPO_ROOT / "train_models.py"
SRC_MODELS_DIR: Path = SRC_DIR / "models"
TRAIN_ENSEMBLE_SCRIPT: Path = SRC_MODELS_DIR / "train_ensemble.py"

# --- Application Outputs ---
# All persistent results generated by the system
FORECASTS_DIR: Path = OUTPUTS_DIR / "forecasts"
MODELS_OUTPUT_DIR: Path = OUTPUTS_DIR / "models"
ALERTS_OUTPUT_DIR: Path = OUTPUTS_DIR / "alerts"
VISUALIZATIONS_DIR: Path = OUTPUTS_DIR / "visualizations"

# --- UI & Dashboard ---
DASHBOARD_APP: Path = SRC_DIR / "dashboard" / "app.py"

# --- Data Pipeline Pipeline Steps ---
# Scripts representing the ETL (Extract, Transform, Load) sequence
DATA_PREPROCESSING_DIR: Path = SRC_DIR / "data_preprocessing"
CLEAN_DATA_SCRIPT: Path = DATA_PREPROCESSING_DIR / "clean_data.py"
FEATURE_ENGINEERING_SCRIPT: Path = DATA_PREPROCESSING_DIR / "feature_engineering.py"
LOAD_DATA_SCRIPT: Path = DATA_PREPROCESSING_DIR / "load_data.py"

# --- Alerting Logic ---
ALERTS_PACKAGE_DIR: Path = SRC_DIR / "alerts"
ALERT_MANAGER_SCRIPT: Path = ALERTS_PACKAGE_DIR / "alert_manager.py"

# --- Runtime Validation ---
# Use this list to programmatically verify that the environment is set up 
# correctly before running data-intensive tasks.
REQUIRED_DIRS = [
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    OUTPUTS_DIR,
    FORECASTS_DIR,
    MODELS_OUTPUT_DIR,
    ALERTS_OUTPUT_DIR,
    VISUALIZATIONS_DIR,
]

# Example usage for developers:
# ----------------------------
# from src.config import settings
# import pandas as pd
# 
# if settings.RAW_AIR_QUALITY_CSV.exists():
#     df = pd.read_csv(settings.RAW_AIR_QUALITY_CSV)